export const IMAGE_HOSTS: string[] = [
  "imx.to",
  "imagebam.com",
  "pixhost.to",
  "imgbox.com",
  "vipr.im",
  "imagetwist.com",
  "postimg.cc",
  "postimg.org",
  "turboimagehost.com",
  "imgur.com",
  "fastpic.org",
  "imgxxt.in",
  "imgdrive.net",
  "pimpandhost.com",
  "imagevenue.com",
];

export const HOST_MAP: [string, string][] = [
  ["imx.to", "extractImxTo"],
  ["imagebam.com", "extractImagebam"],
  ["pixhost.cc", "extractPixhost"],
  ["vipr.im", "extractViprIm"],
  ["imagetwist.com", "extractImagetwist"],
  ["postimg.cc", "extractPostimg"],
  ["postimg.org", "extractPostimg"],
  ["imgbox.com", "extractImgbox"],
  ["turboimagehost.com", "extractTurboimagehost"],
  ["imgur.com", "extractImgur"],
  ["fastpic.org", "extractFastpic"],
  ["imgxxt.in", "extractImgxxt"],
  ["imgdrive.net", "extractImgdrive"],
  ["pimpandhost.com", "extractPimpandhost"],
  ["imagevenue.com", "extractImagevenue"],
];
